services:

  doctrine.orm.yaml_driver:
    class: Doctrine\ORM\Mapping\Driver\SimplifiedYamlDriver
    arguments: [{"%app.root%/Resources/config/doctrine" : WArslett\TweetSync\Model}]

  doctrine.orm.config:
    class: Doctrine\ORM\Configuration
    factory: [Doctrine\ORM\Tools\Setup, createConfiguration]
    calls:
      - [setMetadataDriverImpl, ['@doctrine.orm.yaml_driver']]

  doctrine.orm.entity_manager:
    class: Doctrine\ORM\EntityManager
    factory: [Doctrine\ORM\EntityManager, create]
    arguments:
      - %database.config%
      - '@doctrine.orm.config'

  warslett_tweet_sync_init_command:
    class: WArslett\TweetSyncDoctrine\Console\InitCommand
    arguments: ['@doctrine.orm.entity_manager']
    tags:
